version: "2"
services:
  ode_wrapper:
    build: ode-wrapper
    restart: always
    environment:
      SERVER_PORT: ${WRAPPER_SERVER_PORT}
      CONFIG_ODE_URL: ${WRAPPER_CONFIG_ODE_URL}
      CONFIG_DB_URL: ${WRAPPER_CONFIG_DB_URL}
      CONFIG_DB_USERNAME: ${WRAPPER_CONFIG_DB_USERNAME}
      CONFIG_DB_PASSWORD: ${WRAPPER_CONFIG_DB_PASSWORD}
      CONFIG_MAXIMUM_POOL_SIZE: ${WRAPPER_CONFIG_MAXIMUM_POOL_SIZE}
      CONFIG_CONNECTION_TIMEOUT: ${WRAPPER_CONFIG_CONNECTION_TIMEOUT}
      CONFIG_ENV: ${WRAPPER_CONFIG_ENV}
      CONFIG_SDW_TTL: ${WRAPPER_CONFIG_SDW_TTL}
      CONFIG_SDW_REST_URL: ${SDW_REST_URL}
      CONFIG_SDW_API_KEY: ${SDW_API_KEY}
      CONFIG_ALERT_ADDRESSES: ${WRAPPER_CONFIG_ALERT_ADDRESSES}
      CONFIG_FROM_EMAIL: ${WRAPPER_CONFIG_FROM_EMAIL}
      CONFIG_MAIL_HOST: ${MAIL_HOST}
      CONFIG_MAIL_PORT: ${MAIL_PORT}
      CONFIG_ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
      CONFIG_DEFAULT_LANE_WIDTH: ${WRAPPER_CONFIG_DEFAULT_LANE_WIDTH}
      CONFIG_CV_REST_SERVICE: ${WRAPPER_CONFIG_CV_REST_SERVICE}
      CONFIG_HTTP_LOGGING_MAX_SIZE: ${WRAPPER_CONFIG_HTTP_LOGGING_MAX_SIZE}
      CONFIG_RSU_ROUTES: ${WRAPPER_CONFIG_RSU_ROUTES}
      CONFIG_POINT_INCIDENT_BUFFER_MILES: ${WRAPPER_CONFIG_POINT_INCIDENT_BUFFER_MILES}
      SERVER_SSL_KEY_STORE: ${WRAPPER_SERVER_SSL_KEY_STORE}
      SERVER_SSL_KEY_STORE_PASSWORD: ${WRAPPER_SERVER_SSL_KEY_STORE_PASSWORD}
      SERVER_SSL_KEY_STORE_TYPE: ${WRAPPER_SERVER_SSL_KEY_STORE_TYPE}
      SERVER_SSL_KEY_ALIAS: ${WRAPPER_SERVER_SSL_KEY_ALIAS}
    ports:
      - "7777:7777"
    volumes:
      - /home/timmadmin/timm/ode-wrapper:/keystore
    logging:
      options:
        max-size: "20m"
        max-file: "3"

  cv-data-tasks:
    build: cv-data-tasks
    restart: always
    environment:
      CONFIG_ODE_URL: ${TASKS_CONFIG_ODE_URL}
      CONFIG_CV_REST_SERVICE: ${TASKS_CONFIG_CV_REST_SERVICE}
      CONFIG_CV_REST_SERVICE_DEV: ${TASKS_CONFIG_CV_REST_SERVICE_DEV}
      CONFIG_CV_REST_SERVICE_PROD: ${TASKS_CONFIG_CV_REST_SERVICE_PROD}
      CONFIG_RSU_DATA_SERVICE_URL: ${TASKS_CONFIG_RSU_DATA_SERVICE_URL}
      CONFIG_WRAPPER_URL: ${TASKS_CONFIG_WRAPPER_URL}
      CONFIG_MAIL_HOST: ${MAIL_HOST}
      CONFIG_MAIL_PORT: ${MAIL_PORT}
      CONFIG_ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
      CONFIG_SDW_REST_URL: ${SDW_REST_URL}
      CONFIG_SDW_API_KEY: ${SDW_API_KEY}
      CONFIG_TMDD_URL: ${TASKS_CONFIG_TMDD_URL}
      CONFIG_TMDD_USER: ${TASKS_CONFIG_TMDD_USER}
      CONFIG_TMDD_PASSWORD: ${TASKS_CONFIG_TMDD_PASSWORD}
      CONFIG_ALERT_ADDRESSES: ${TASKS_CONFIG_ALERT_ADDRESSES}
      CONFIG_FROM_EMAIL: ${TASKS_CONFIG_FROM_EMAIL}
      CONFIG_RUN_TMDD_VALIDATION: ${TASKS_CONFIG_RUN_TMDD_VALIDATION}
      CONFIG_RUN_RSU_VALIDATION: ${TASKS_CONFIG_RUN_RSU_VALIDATION}
      CONFIG_RSU_VALIDATION_DELAY_SECONDS: ${TASKS_CONFIG_RSU_VALIDATION_DELAY_SECONDS}
      CONFIG_RSU_VAL_THREAD_POOL_SIZE: ${TASKS_CONFIG_RSU_VAL_THREAD_POOL_SIZE}
      CONFIG_RSU_VAL_TIMEOUT_SECONDS: ${TASKS_CONFIG_RSU_VAL_TIMEOUT_SECONDS}
      CONFIG_REMOVE_EXPIRED_PERIOD_MINUTES: ${TASKS_CONFIG_REMOVE_EXPIRED_PERIOD_MINUTES}
      CONFIG_CLEANUP_PERIOD_MINUTES: ${TASKS_CONFIG_CLEANUP_PERIOD_MINUTES}
      CONFIG_SDX_VALIDATION_PERIOD_MINUTES: ${TASKS_CONFIG_SDX_VALIDATION_PERIOD_MINUTES}
      CONFIG_RSU_VALIDATION_PERIOD_MINUTES: ${TASKS_CONFIG_RSU_VALIDATION_PERIOD_MINUTES}
      CONFIG_TMDD_VALIDATION_PERIOD_MINUTES: ${TASKS_CONFIG_TMDD_VALIDATION_PERIOD_MINUTES}
      CONFIG_RETENTION_ENFORCEMENT_PERIOD_MINUTES: ${TASKS_CONFIG_RETENTION_ENFORCEMENT_PERIOD_MINUTES}
      CONFIG_RETENTION_REMOVE_TIMS: ${TASKS_CONFIG_RETENTION_REMOVE_TIMS}
      CONFIG_RETENTION_REMOVE_STATUS_LOGS: ${TASKS_CONFIG_RETENTION_REMOVE_STATUS_LOGS}
      CONFIG_HSM_FUNCTIONALITY_MINUTES: ${TASKS_CONFIG_HSM_FUNCTIONALITY_MINUTES}
      CONFIG_HSM_URL: ${TASKS_CONFIG_HSM_URL}
      CONFIG_HSM_ERROR_EMAIL_FREQUENCY_MINUTES: ${TASKS_CONFIG_HSM_ERROR_EMAIL_FREQUENCY_MINUTES}
      CONFIG_RUN_HSM_CHECK: ${TASKS_CONFIG_RUN_HSM_CHECK}
      CONFIG_SDW_TTL: ${TASKS_CONFIG_SDW_TTL}
      CONFIG_DEFAULT_LANE_WIDTH: ${TASKS_CONFIG_DEFAULT_LANE_WIDTH}
      CONFIG_RSU_ROUTES: ${TASKS_CONFIG_RSU_ROUTES}
      CONFIG_POINT_INCIDENT_BUFFER_MILES: ${TASKS_CONFIG_POINT_INCIDENT_BUFFER_MILES}
    logging:
      options:
        max-size: "20m"
        max-file: "3"
    depends_on:
      - ode_wrapper
      - cv-data-controller
      - rsu-data-controller

  tim-refresh:
    build: tim-refresh
    restart: always
    environment:
      CONFIG_ODE_URL: ${REFRESH_CONFIG_ODE_URL}
      CONFIG_SDW_TTL: ${REFRESH_CONFIG_SDW_TTL}
      CONFIG_CV_REST_SERVICE: ${REFRESH_CONFIG_CV_REST_SERVICE}
      CONFIG_SDW_REST_URL: ${SDW_REST_URL}
      CONFIG_SDW_API_KEY: ${SDW_API_KEY}
      CONFIG_DEFAULT_LANE_WIDTH: ${REFRESH_CONFIG_DEFAULT_LANE_WIDTH}
      CONFIG_RSU_ROUTES: ${REFRESH_CONFIG_RSU_ROUTES}
      CONFIG_POINT_INCIDENT_BUFFER_MILES: ${REFRESH_CONFIG_POINT_INCIDENT_BUFFER_MILES}
      CRON_EXPRESSION: ${REFRESH_CRON_EXPRESSION}
      CONFIG_ENV: ${REFRESH_CONFIG_ENV}
      CONFIG_ALERT_ADDRESSES: ${REFRESH_CONFIG_ALERT_ADDRESSES}
      CONFIG_FROM_EMAIL: ${REFRESH_CONFIG_FROM_EMAIL}
      CONFIG_ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
      CONFIG_MAIL_HOST: ${MAIL_HOST}
      CONFIG_MAIL_PORT: ${MAIL_PORT}
    logging:
      options:
        max-size: "20m"
        max-file: "3"

  cv-data-controller:
    build: cv-data-controller
    restart: always
    ports:
      - "8888:8888"
    environment:
      SERVER_PORT: ${CONTROLLER_SERVER_PORT}
      CONFIG_DB_URL: ${CONTROLLER_CONFIG_DB_URL}
      CONFIG_DB_USERNAME: ${CONTROLLER_CONFIG_DB_USERNAME}
      CONFIG_DB_PASSWORD: ${CONTROLLER_CONFIG_DB_PASSWORD}
      CONFIG_MAXIMUM_POOL_SIZE: ${CONTROLLER_CONFIG_MAXIMUM_POOL_SIZE}
      CONFIG_CONNECTION_TIMEOUT: ${CONTROLLER_CONFIG_CONNECTION_TIMEOUT}
      CONFIG_ODE_URL: ${CONTROLLER_CONFIG_ODE_URL}
      CONFIG_ENV: ${CONTROLLER_CONFIG_ENV}
      SPRING_DATA_NEO4J_URI: ${CONTROLLER_SPRING_DATA_NEO4J_URI}
      CONFIG_ALERT_ADDRESSES: ${CONTROLLER_CONFIG_ALERT_ADDRESSES}
      CONFIG_FROM_EMAIL: ${CONTROLLER_CONFIG_FROM_EMAIL}
      CONFIG_ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
      CONFIG_MAIL_HOST: ${MAIL_HOST}
      CONFIG_MAIL_PORT: ${MAIL_PORT}
      SERVER_SSL_KEY_STORE: ${CONTROLLER_SERVER_SSL_KEY_STORE}
      SERVER_SSL_KEY_STORE_PASSWORD: ${CONTROLLER_SERVER_SSL_KEY_STORE_PASSWORD}
      SERVER_SSL_KEY_STORE_TYPE: ${CONTROLLER_SERVER_SSL_KEY_STORE_TYPE}
      SERVER_SSL_KEY_ALIAS: ${CONTROLLER_SERVER_SSL_KEY_ALIAS}
    volumes:
      - /home/timmadmin/timm/cv-data-controller:/keystore
    logging:
      options:
        max-size: "20m"
        max-file: "3"

  rsu-data-controller:
    build: rsu-data-controller
    restart: always
    ports:
      - "8898:8898"
    environment:
      SERVER_PORT: ${RSUCONTROLLER_SERVER_PORT}
      CONFIG_SNMP_RETRIES: ${RSUCONTROLLER_CONFIG_SNMP_RETRIES}
      CONFIG_SNMP_TIMEOUT_SECONDS: ${RSUCONTROLLER_CONFIG_SNMP_TIMEOUT_SECONDS}
      CONFIG_SNMP_USER_NAME: ${RSUCONTROLLER_CONFIG_SNMP_USER_NAME}
      CONFIG_SNMP_AUTH_PASSPHRASE: ${RSUCONTROLLER_CONFIG_SNMP_AUTH_PASSPHRASE}
      CONFIG_SNMP_AUTH_PROTOCOL: ${RSUCONTROLLER_CONFIG_SNMP_AUTH_PROTOCOL}
      CONFIG_SNMP_SECURITY_LEVEL: ${RSUCONTROLLER_CONFIG_SNMP_SECURITY_LEVEL}
    logging:
      options:
        max-size: "20m"
        max-file: "3"

  tim_logger_mongo:
    build: ode-mongo-logger
    restart: always
    environment:
      MONGOLOGGER_DEPOSIT_TOPIC: ${TIM_TOPIC}
      MONGOLOGGER_DEPOSIT_GROUP: ${TIM_GROUP_MONGO}
      MONGOLOGGER_HOSTNAME: ${MONGO_HOSTNAME}
      MONGOLOGGER_MONGO_HOST: ${MONGO_HOST}
      MONGOLOGGER_MONGO_DATABASE: ${MONGO_DATABASE}
      MONGOLOGGER_MONGO_AUTH_DATABASE: ${MONGO_AUTH_DATABASE}
      MONGOLOGGER_MONGO_USERNAME: ${MONGO_USERNAME}
      MONGOLOGGER_MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGOLOGGER_ALERT_ADDRESSES: ${MONGO_ALERT_ADDRESSES}
      MONGOLOGGER_FROM_EMAIL: ${MONGO_FROM_EMAIL}
      MONGOLOGGER_ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
      MONGOLOGGER_MAIL_HOST: ${MAIL_HOST}
      MONGOLOGGER_MAIL_PORT: ${MAIL_PORT}
    logging:
      options:
        max-size: "20m"
        max-file: "3"

  bsm_logger_mongo:
    build: ode-mongo-logger
    restart: always
    environment:
      MONGOLOGGER_DEPOSIT_TOPIC: ${BSM_TOPIC}
      MONGOLOGGER_DEPOSIT_GROUP: ${BSM_GROUP_MONGO}
      MONGOLOGGER_HOSTNAME: ${MONGO_HOSTNAME}
      MONGOLOGGER_MONGO_HOST: ${MONGO_HOST}
      MONGOLOGGER_MONGO_DATABASE: ${MONGO_DATABASE}
      MONGOLOGGER_MONGO_AUTH_DATABASE: ${MONGO_AUTH_DATABASE}
      MONGOLOGGER_MONGO_USERNAME: ${MONGO_USERNAME}
      MONGOLOGGER_MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGOLOGGER_ALERT_ADDRESSES: ${MONGO_ALERT_ADDRESSES}
      MONGOLOGGER_FROM_EMAIL: ${MONGO_FROM_EMAIL}
      MONGOLOGGER_ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
      MONGOLOGGER_MAIL_HOST: ${MAIL_HOST}
      MONGOLOGGER_MAIL_PORT: ${MAIL_PORT}
    logging:
      options:
        max-size: "20m"
        max-file: "3"

  driveralert_logger_mongo:
    build: ode-mongo-logger
    restart: always
    environment:
      MONGOLOGGER_DEPOSIT_TOPIC: ${DA_TOPIC}
      MONGOLOGGER_DEPOSIT_GROUP: ${DA_GROUP_MONGO}
      MONGOLOGGER_HOSTNAME: ${MONGO_HOSTNAME}
      MONGOLOGGER_MONGO_HOST: ${MONGO_HOST}
      MONGOLOGGER_MONGO_DATABASE: ${MONGO_DATABASE}
      MONGOLOGGER_MONGO_AUTH_DATABASE: ${MONGO_AUTH_DATABASE}
      MONGOLOGGER_MONGO_USERNAME: ${MONGO_USERNAME}
      MONGOLOGGER_MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGOLOGGER_ALERT_ADDRESSES: ${MONGO_ALERT_ADDRESSES}
      MONGOLOGGER_FROM_EMAIL: ${MONGO_FROM_EMAIL}
      MONGOLOGGER_ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
      MONGOLOGGER_MAIL_HOST: ${MAIL_HOST}
      MONGOLOGGER_MAIL_PORT: ${MAIL_PORT}
    logging:
      options:
        max-size: "20m"
        max-file: "3"

  tim_logger:
    build: ode-data-logger
    restart: always
    environment:
      KAFKA_HOST_SERVER: ${LOGGER_KAFKA_HOST_SERVER}
      ALERT_ADDRESSES: ${LOGGER_ALERT_ADDRESSES}
      FROM_EMAIL: ${LOGGER_FROM_EMAIL}
      ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      DEPOSIT_TOPIC: ${TIM_TOPIC}
      DEPOSIT_GROUP: ${TIM_GROUP_ORACLE}
      CV_REST_SERVICE: ${LOGGER_CV_REST_SERVICE}
      PRODUCER_TOPIC: ${DBCONSUMER_DEPOSIT_TOPIC}
      ENV: ${LOGGER_ENV}
    logging:
      options:
        max-size: "20m"
        max-file: "3"

  logger-kafka-consumer:
    build: logger-kafka-consumer
    restart: always
    environment:
      DEPOSIT_GROUP: ${DBCONSUMER_DEPOSIT_GROUP}
      DEPOSIT_TOPIC: ${DBCONSUMER_DEPOSIT_TOPIC}
      KAFKA_HOST_SERVER: ${DBCONSUMER_KAFKA_HOST_SERVER}
      MAX_POLL_INTERVAL_MS: ${DBCONSUMER_MAX_POLL_INTERVAL_MS}
      MAX_POLL_RECORDS: ${DBCONSUMER_MAX_POLL_RECORDS}
      DB_URL: ${DBCONSUMER_DB_URL}
      DB_USERNAME: ${DBCONSUMER_DB_USERNAME}
      DB_PASSWORD: ${DBCONSUMER_DB_PASSWORD}
      MAXIMUM_POOL_SIZE: ${DBCONSUMER_MAXIMUM_POOL_SIZE}
      CONNECTION_TIMEOUT: ${DBCONSUMER_CONNECTION_TIMEOUT}
      ALERT_ADDRESSES: ${DBCONSUMER_ALERT_ADDRESSES}
      FROM_EMAIL: ${DBCONSUMER_FROM_EMAIL}
      ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      ENV: ${DBCONSUMER_ENV}
    logging:
      options:
        max-size: "20m"
        max-file: "3"

  milepost-graph-db:
    build: milepost-graph-db
    restart: always
    ports:
      - "6474:7474"
      - "6473:7473"
      - "6687:7687"
    volumes:
      - ./milepost-graph-db/neo-data/plugins:/var/lib/neo4j/plugins
      - ./milepost-graph-db/neo-data/import:/var/lib/neo4j/import
      - ./milepost-graph-db/neo-data/conf:/var/lib/neo4j/conf
      - ./milepost-graph-db/neo-data/data:/var/lib/neo4j/data
    environment:
      NEO4J_AUTH: none
    logging:
      options:
        max-size: "20m"
        max-file: "3"

  cert-expiration:
    build: cert-expiration
    restart: always
    environment:
      KAFKA_HOST_SERVER: ${LOGGER_KAFKA_HOST_SERVER}
      ENV: ${LOGGER_ENV}
      ALERT_ADDRESSES: ${LOGGER_ALERT_ADDRESSES}
      FROM_EMAIL: ${LOGGER_FROM_EMAIL}
      ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      DEPOSIT_TOPIC: ${EXP_TOPIC}
      DEPOSIT_GROUP: ${EXP_GROUP}
      CV_REST_SERVICE: ${LOGGER_CV_REST_SERVICE}
      PRODUCER_TOPIC: ${DBCONSUMER_DEPOSIT_TOPIC}
    logging:
      options:
        max-size: "20m"
        max-file: "3"