FROM maven:3.8-eclipse-temurin-21-alpine

ADD . /home/wyocv/wyocv_applications/logger-kafka-consumer

CMD java -jar /home/wyocv/wyocv_applications/logger-kafka-consumer/logger-kafka-consumer-1.3.0-SNAPSHOT.jar
