FROM maven:3.8-eclipse-temurin-21-alpine

ADD . /home/timm/timm_applications/logger-kafka-consumer

CMD java -jar /home/timm/timm_applications/logger-kafka-consumer/logger-kafka-consumer-1.4.0-SNAPSHOT.jar
