version: '3.7'
services:
  milepost-graph:
    build: .
    # image: neo4j:3.5.14
    ports:
      - '6474:7474'
      - '6473:7473'
      - '6687:7687'
    volumes:
      - type: bind
        source: ./neo-data/plugins
        target: /var/lib/neo4j/plugins
      - type: bind
        source: ./neo-data/import
        target: /var/lib/neo4j/import
      - type: bind
        source: ./neo-data/conf
        target: /var/lib/neo4j/conf
      - type: bind
        source: ./neo-data/data
        target: /var/lib/neo4j/data
    environment:
      NEO4J_AUTH: none
