-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.145.9.179;sid=odevdbp01;port=1521

SET client_encoding TO 'UTF8';


-- CREATE OR REPLACE VIEW milepost_vw (route, milepost, direction, latitude, longitude, elevation_ft, bearing) AS SELECT ROUTE,
-- MILEPOST,
-- DIRECTION,
-- LATITUDE,
-- LONGITUDE,
-- ELEVATION_FT,
-- BEARING
-- FROM WEBAPPS.CV_I80_MILEPOST_10THS_FC@WEBAPPS_ODA_DBLINK.GISITS.LOCAL;

-- CREATE OR REPLACE VIEW direction_exceptions (dominant_route_name, direction_reversed, from_mp, to_mp) AS select s.dominant_route_name,
-- s.direction_reversed,
-- e.from_mp,
-- e.to_mp
-- FROM wrr.segroads_join@wrr_oda_dblink.gisits.local s, gis.wti2_events@gis_oda_dblink.gisits.local e
-- where s.default_desc = 'Y'
--   and s.direction_reversed = 'Y'
--   and s.road_code = e.road_code
-- order by dominant_route_name;

-- CREATE OR REPLACE VIEW milepost_10ths_ov_old (lrs_route, common_name, common_name_direction, road_code, milepost, latitude, longitude) AS SELECT ROUTE AS LRS_ROUTE,
--   MILEPOST_CN_LU(ROUTE, ROUTE, MILEPOST) AS COMMON_NAME,
--   --ML80
--   CASE WHEN ROUTE = 'ML80D'
--     THEN 'West'
--     WHEN ROUTE = 'ML80I'
--     THEN 'East'
--     --ML25
--     WHEN ROUTE = 'ML25D'
--     THEN 'South'
--     WHEN ROUTE = 'ML25I'
--     THEN 'North'
--     --ML90
--     WHEN ROUTE = 'ML90D'
--     THEN 'West'
--     WHEN ROUTE = 'ML90I'
--     THEN 'East'
--     --ML12
--     WHEN ROUTE = 'ML12D' AND MILEPOST >= 99.515 AND MILEPOST <= 100.03
--     THEN 'West'
--     WHEN ROUTE = 'ML12I' AND MILEPOST >= 99.515 AND MILEPOST <= 100.03
--     THEN 'East'
--     --ML180
--     WHEN ROUTE = 'ML180D' AND MILEPOST >= 0 AND MILEPOST <= 12.61
--     THEN 'South'
--     WHEN ROUTE = 'ML180I' AND MILEPOST >= 0 AND MILEPOST <= 12.61
--     THEN 'North'
--     --ML21
--     WHEN ROUTE = 'ML21D' AND MILEPOST >= 0.212 AND MILEPOST <= 1.3
--     THEN 'South'
--     WHEN ROUTE = 'ML21I' AND MILEPOST >= 0.212 AND MILEPOST <= 1.3
--     THEN 'North'
--     WHEN ROUTE = 'ML21D' AND MILEPOST >= 103.2 AND MILEPOST <= 115.302
--     THEN 'West'
--     WHEN ROUTE = 'ML21I' AND MILEPOST >= 103.2 AND MILEPOST <= 115.302
--     THEN 'East'
--     --ML23
--     WHEN ROUTE = 'ML23D' AND MILEPOST >= 292.597 AND MILEPOST <= 308.5
--     THEN 'West'
--     WHEN ROUTE = 'ML23I' AND MILEPOST >= 292.597 AND MILEPOST <= 308.5
--     THEN 'East'
--     WHEN ROUTE = 'ML23D' AND MILEPOST >= 415.6 AND MILEPOST <= 419.679
--     THEN 'North'
--     WHEN ROUTE = 'ML23I' AND MILEPOST >= 415.6 AND MILEPOST <= 419.679
--     THEN 'South'
--     --ML27
--     WHEN ROUTE = 'ML27D' AND MILEPOST >= 0 AND MILEPOST <= 0.632
--     THEN 'West'
--     WHEN ROUTE = 'ML27I' AND MILEPOST >= 0 AND MILEPOST <= 0.632
--     THEN 'East'
--     --ML29
--     WHEN ROUTE = 'ML29D' AND MILEPOST >= 23.845 AND MILEPOST <= 39.202
--     THEN 'West'
--     WHEN ROUTE = 'ML29I' AND MILEPOST >= 23.845 AND MILEPOST <= 39.202
--     THEN 'East'
--     --ML30
--     WHEN ROUTE = 'ML30D' AND MILEPOST >= 133.256 AND MILEPOST <= 133.705
--     THEN 'West'
--     WHEN ROUTE = 'ML30I' AND MILEPOST >= 133.256 AND MILEPOST <= 133.705
--     THEN 'East'
--     --ML34
--     WHEN ROUTE = 'ML34D' AND MILEPOST >= 236.347 AND MILEPOST <= 237.359
--     THEN 'South'
--     WHEN ROUTE = 'ML34I' AND MILEPOST >= 236.347 AND MILEPOST <= 237.359
--     THEN 'North'
--     --ML47
--     WHEN ROUTE = 'ML47D' AND MILEPOST >= 0 AND MILEPOST <= 2.9
--     THEN 'West'
--     WHEN ROUTE = 'ML47I' AND MILEPOST >= 0 AND MILEPOST <= 2.9
--     THEN 'East'
--     --ML505
--     WHEN ROUTE = 'ML505D' AND MILEPOST >= 183.787 AND MILEPOST <= 187.272
--     THEN 'East'
--     WHEN ROUTE = 'ML505I' AND MILEPOST >= 183.787 AND MILEPOST <= 187.272
--     THEN 'West'
--     --ML56
--     WHEN ROUTE = 'ML56D' AND MILEPOST >= 359.2 AND MILEPOST <= 359.5
--     THEN 'West'
--     WHEN ROUTE = 'ML56I' AND MILEPOST >= 359.2 AND MILEPOST <= 359.5
--     THEN 'East'
--     WHEN ROUTE = 'ML56D' AND MILEPOST >= 359.6 AND MILEPOST <= 366.688
--     THEN 'West'
--     WHEN ROUTE = 'ML56I' AND MILEPOST >= 359.6 AND MILEPOST <= 366.688
--     THEN 'East'
--     --ML85
--     WHEN ROUTE = 'ML85D' AND MILEPOST >= 16.94 AND MILEPOST <= 17.323
--     THEN 'South'
--     WHEN ROUTE = 'ML85I' AND MILEPOST >= 16.94 AND MILEPOST <= 17.323
--     THEN 'North'
--     --Georgia
--     WHEN ROUTE = 'GA001D'
--     THEN 'South'
--     WHEN ROUTE = 'GA001I'
--     THEN 'North'
--     --Virginia
--     WHEN ROUTE = 'VA60D'
--     THEN 'West'
--     WHEN ROUTE = 'VA60I'
--     THEN 'East'
--   ELSE '' END AS COMMON_NAME_DIRECTION,
--   MILEPOST_RC_LU(ROUTE, MILEPOST) AS ROAD_CODE,
--   MILEPOST,
--   LATITUDE,
--   LONGITUDE
-- FROM GIS.ELRS_MILEPOST_10THS_WYAL_FC;

CREATE OR REPLACE VIEW milepost_vw_new (common_name, direction, milepost, latitude, longitude) AS SELECT DISTINCT COMMON_NAME,
DIRECTION,
MILEPOST,
LATITUDE,
LONGITUDE
FROM MILEPOSTS;

-- CREATE OR REPLACE VIEW wti2_events_ov (route, from_mp, to_mp, road_code, dominant_route_name) AS SELECT t.CATEGORY || t.ID_NUMBER || t.DIRECTION AS ROUTE,
--   t.FROM_MP,
--   t.TO_MP,
--   t.ROAD_CODE,
--   s.DOMINANT_ROUTE_NAME
-- FROM GIS.WTI2_EVENTS t
-- LEFT OUTER JOIN(SELECT DISTINCT ROAD_CODE, DOMINANT_ROUTE_NAME FROM WRR.SEGROADS_JOIN) s ON t.ROAD_CODE = s.ROAD_CODE;

-- CREATE OR REPLACE VIEW route_directionality (route, directionality) AS select route_name(route) as route,
-- directionality
-- FROM (select substr(segment_id, 1, length(segment_id)-2) as route,
--       directionality
--       from wrr.segments@wrr_oda_dblink.gisits.local
--       where substr(segment_id, 1, length(segment_id)-2) not in ('SRCASP', 'SRCHEY', 'SRCHUG', 'SRRS', 'TR888', 'TR999')
--         and directionality is not null
--       group by substr(segment_id, 1, length(segment_id)-2), directionality
--       order by substr(segment_id, 1, length(segment_id)-2)) alias10;

-- CREATE OR REPLACE VIEW milepost_10ths_ov (lrs_route, common_name, direction, road_code, milepost, latitude, longitude) AS SELECT ROUTE AS LRS_ROUTE,
--   MILEPOST_CN_LU(ROUTE, ROUTE, MILEPOST) AS COMMON_NAME,
--   --ML80
--   CASE
--     WHEN ROUTE LIKE '%D' THEN
--       'D'
--     WHEN ROUTE LIKE '%I' THEN
--       'I'
--     ELSE
--       'B'
--   END AS DIRECTION,
--   MILEPOST_RC_LU(ROUTE, MILEPOST) AS ROAD_CODE,
--   MILEPOST,
--   LATITUDE,
--   LONGITUDE
-- FROM GIS.ELRS_MILEPOST_10THS_WYAL_FC@GIS_ODA_DBLINK.GISITS.LOCAL;

-- CREATE OR REPLACE VIEW rsu_vw (deviceid, sitename, devicename, devicetype, manufactname, modeldescription, modelnumber, status, latitude, longitude, category, idnumber, direction, route, milepost, powertype, commdesc, district, ipv4_address, ipv6_address) AS SELECT DEVICEID,
-- SITENAME,
-- DEVICENAME,
-- DEVICETYPE,
-- MANUFACTNAME,
-- MODELDESCRIPTION,
-- MODELNUMBER,
-- STATUS,
-- LATITUDE,
-- LONGITUDE,
-- CATEGORY,
-- IDNUMBER,
-- DIRECTION,
-- RSU_ROUTE(CATEGORY || IDNUMBER || DIRECTION, round((MILEPOST)::numeric,1)) AS ROUTE,
-- MILEPOST,
-- POWERTYPE,
-- COMMDESC,
-- DISTRICT,
-- IPV4_ADDRESS,
-- IPV6_ADDRESS
-- FROM ITS.RSU_VW@ITS_ODA_DBLINK.GISITS.LOCAL;

-- CREATE OR REPLACE VIEW milepost_vw_old (route, milepost, direction, latitude, longitude, elevation_ft, bearing) AS SELECT ROUTE,
-- MILEPOST,
-- DIRECTION,
-- LATITUDE,
-- LONGITUDE,
-- ELEVATION_FT,
-- BEARING
-- FROM WEBAPPS.CV_I80_MILEPOST_10THS_FC@WEBAPPS_ODA_DBLINK.GISITS.LOCAL;

-- CREATE OR REPLACE VIEW milepost_cn_lu_ov (route, from_mp, to_mp, dominant_route_name) AS SELECT ROUTE,
--   FROM_MP,
--   TO_MP,
--   DOMINANT_ROUTE_NAME
-- FROM WTI2_EVENTS_OV
-- WHERE DOMINANT_ROUTE_NAME NOT IN ('Cheyenne Service Road', 'Chugwater Service Road', 'Rock Springs Service Road', 'Casper Service Road');

-- CREATE OR REPLACE VIEW milepost_rc_lu_ov (route, from_mp, to_mp, road_code) AS SELECT ROUTE,
--   FROM_MP,
--   TO_MP,
--   ROAD_CODE
-- FROM WTI2_EVENTS_OV;


