-- Rename old TIM_RSU table, constraints, etc.
ALTER TABLE TIM_RSU_OLD DROP CONSTRAINT FK_RSU;
ALTER TABLE TIM_RSU_OLD DROP CONSTRAINT FK_TIM_RSU;
ALTER TABLE TIM_RSU_OLD DROP CONSTRAINT SYS_C0013318;
ALTER TABLE TIM_RSU_OLD DROP CONSTRAINT SYS_C0013319;
ALTER TABLE TIM_RSU_OLD DROP CONSTRAINT SYS_C0013320;
ALTER TABLE TIM_RSU_OLD DROP CONSTRAINT TIM_RSU_PK;
DROP INDEX TIM_RSU_PK;
DROP TRIGGER TRG_TIM_RSU_ID;

ALTER TABLE TIM_RSU_OLD RENAME TO TIM_RSU_OLD;

COMMIT;

-- Create new TIM_RSU table
CREATE TABLE "CVCOMMS"."TIM_RSU" 
(	"TIM_RSU_ID" NUMBER(10,0) NOT NULL, 
    "RSU_ID" NUMBER(10,0) NOT NULL REFERENCES "CVCOMMS"."RSU" ("RSU_ID") ON DELETE CASCADE ENABLE, 
    "TIM_ID" NUMBER(10,0) NOT NULL REFERENCES "CVCOMMS"."TIM" ("TIM_ID") ON DELETE CASCADE ENABLE, 
    "RSU_INDEX" NUMBER(10,0)
)   NO INMEMORY ;

-- Create trigger
CREATE OR REPLACE EDITIONABLE TRIGGER "CVCOMMS"."TRG_TIM_RSU_ID" 
before insert on tim_rsu
for each row
begin
select tim_rsu_id_seq.nextval
into :new.tim_rsu_id
from dual;
end;

/
ALTER TRIGGER "CVCOMMS"."TRG_TIM_RSU_ID" ENABLE;

-- PK index
CREATE UNIQUE INDEX "CVCOMMS"."TIM_RSU_PK" ON "CVCOMMS"."TIM_RSU" ("TIM_RSU_ID");

-- Constraints
ALTER TABLE "CVCOMMS"."TIM_RSU" ADD CONSTRAINT "TIM_RSU_U" UNIQUE (rsu_id, tim_id, rsu_index)
USING INDEX  ENABLE;
ALTER TABLE "CVCOMMS"."TIM_RSU" ADD CONSTRAINT "TIM_RSU_PK" PRIMARY KEY ("TIM_RSU_ID")
USING INDEX  ENABLE;

COMMIT;

-- Insert old data
INSERT INTO TIM_RSU(rsu_id, tim_id, rsu_index)
SELECT DISTINCT rsu_id, tim_id, rsu_index FROM TIM_RSU_OLD;

COMMIT;

-- DROP TIM_RSU_OLD

