ALTER TABLE DATA_FRAME_ITIS_CODE
ADD POSITION NUMBER(2); -- [0, 99] Per J2735, ITIScodesAndText can have up to 100 elements

INSERT INTO ITIS_CODE (DESCRIPTION, CATEGORY_ID, ITIS_CODE) VALUES (10, 1, 12554);
INSERT INTO ITIS_CODE (DESCRIPTION, CATEGORY_ID, ITIS_CODE) VALUES (15, 1, 12559);
INSERT INTO ITIS_CODE (DESCRIPTION, CATEGORY_ID, ITIS_CODE) VALUES (20, 1, 12564);
INSERT INTO ITIS_CODE (DESCRIPTION, CATEGORY_ID, ITIS_CODE) VALUES (25, 1, 12569);
INSERT INTO ITIS_CODE (DESCRIPTION, CATEGORY_ID, ITIS_CODE) VALUES (30, 1, 12574);