--------------------------------------------------------
--  File created - Tuesday-August-04-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence BSM_PART2_SUVE_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CVCOMMS"."BSM_PART2_SUVE_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 31907664 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Table BSM_PART2_SUVE
--------------------------------------------------------

  CREATE TABLE "CVCOMMS"."BSM_PART2_SUVE" 
   (	"BSM_PART2_SUVE_ID" NUMBER(10,0) NOT NULL, 
	"BSM_CORE_DATA_ID" NUMBER(10,0) NOT NULL, 
	"ID" VARCHAR2(255 BYTE), 
	"CLASSIFICATION" NUMBER(10,0), 
	"CD_FUELTYPE" VARCHAR2(20 BYTE), 
	"CD_HPMSTYPE" VARCHAR2(20 BYTE), 
	"CD_ISO3883" NUMBER(10,0), 
	"CD_KEYTYPE" NUMBER(10,0), 
	"CD_REGIONAL" VARCHAR2(1000 BYTE), 
	"CD_RESPONDERTYPE" VARCHAR2(50 BYTE), 
	"CD_RESPONSEEQUIP_NAME" VARCHAR2(255 BYTE), 
	"CD_RESPONSEEQUIP_VALUE" NUMBER(19,0), 
	"CD_ROLE" VARCHAR2(20 BYTE), 
	"CD_VEHICLETYPE_NAME" VARCHAR2(255 BYTE), 
	"CD_VEHICLETYPE_VALUE" NUMBER(19,0), 
	"VD_BUMPERS_FRONT" NUMBER(15,5), 
	"VD_BUMPERS_REAR" NUMBER(15,5), 
	"VD_HEIGHT" NUMBER(15,5), 
	"VD_MASS" NUMBER(10,0), 
	"VD_TRAILERWEIGHT" NUMBER(10,0), 
	"WR_FRICTION" NUMBER(10,0), 
	"WR_ISRAINING" VARCHAR2(10 BYTE), 
	"WR_PRECIPSITUATION" VARCHAR2(30 BYTE), 
	"WR_RAINRATE" NUMBER(15,5), 
	"WR_ROADFRICTION" NUMBER(15,5), 
	"WR_SOLARRADIATION" NUMBER(10,0), 
	"WP_AIRPRESSURE" NUMBER(10,0), 
	"WP_AIRTEMP" NUMBER(10,0), 
	"WP_RAINRATES_RATEFRONT" NUMBER(10,0), 
	"WP_RAINRATES_RATEREAR" NUMBER(10,0), 
	"WP_RAINRATES_STATUSFRONT" VARCHAR2(20 BYTE), 
	"WP_RAINRATES_STATUSREAR" VARCHAR2(20 BYTE), 
	"OB_DATETIME" DATE, 
	"OB_DESCRIPTION" NUMBER(10,0), 
	"OB_LOCATIONDETAILS_NAME" VARCHAR2(255 BYTE), 
	"OB_LOCATIONDETAILS_VALUE" NUMBER(19,0), 
	"OB_OBDIRECT" NUMBER(38,0), 
	"OB_OBDIST" NUMBER(10,0), 
	"OB_VERTEVENT" VARCHAR2(1000 BYTE), 
	"ST_STATUSDETAILS" NUMBER(10,0), 
	"ST_LOCATIONDETAILS_NAME" VARCHAR2(255 BYTE), 
	"ST_LOCATIONDETAILS_VALUE" NUMBER(19,0), 
	"SP_SPEEDREPORTS" VARCHAR2(1000 BYTE), 
	"RTCM_MSGS" VARCHAR2(1000 BYTE), 
	"RTCM_HEADER_ANTOFFSETX" NUMBER(15,5), 
	"RTCM_HEADER_ANTOFFSETY" NUMBER(15,5), 
	"RTCM_HEADER_ANTOFFSETZ" NUMBER(15,5), 
	"RTCM_RTCMHEADER_STATUS" VARCHAR2(1000 BYTE), 
	"REGIONAL" VARCHAR2(1000 BYTE),
    CONSTRAINT "FK_BSM_CORE_DATA_SUVE" FOREIGN KEY ("BSM_CORE_DATA_ID") REFERENCES "CVCOMMS"."BSM_CORE_DATA" ("BSM_CORE_DATA_ID") ON DELETE CASCADE
   )  -- NO INMEMORY 
      -- PARTITION BY REFERENCE("FK_BSM_CORE_DATA_SUVE");
       
--------------------------------------------------------
--  DDL for Index IX_BSMPART2SUVE_BSMCOREDATAID
--------------------------------------------------------

  CREATE INDEX "CVCOMMS"."IX_BSMPART2SUVE_BSMCOREDATAID" ON "CVCOMMS"."BSM_PART2_SUVE" ("BSM_CORE_DATA_ID") 
  ;
--------------------------------------------------------
--  DDL for Trigger TRG_BSM_PART2_SUVE_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CVCOMMS"."TRG_BSM_PART2_SUVE_ID" 
before insert on bsm_part2_suve
for each row
begin
select bsm_part2_suve_id_seq.nextval
into :new.bsm_part2_suve_id
from dual;
end;

/
ALTER TRIGGER "CVCOMMS"."TRG_BSM_PART2_SUVE_ID" ENABLE;
--------------------------------------------------------
--  DDL for Synonymn DUAL
--------------------------------------------------------

  --CREATE OR REPLACE NONEDITIONABLE PUBLIC SYNONYM "DUAL" FOR "SYS"."DUAL";
